config/routes.rb
Chambers::Engine.routes.draw do
  resources :chambers
end

app/models/chambers/application_record.rb
module Chambers
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/chambers/chamber.rb
module Chambers
  ##
  # Chamber is the moniker for a room.  This model will be the core of the entire Chambers service.
  
  class Chamber < ApplicationRecord

    has_one :key, :class_name => "ChamberKey", primary_key: :uuid, foreign_key: :chamber_uuid

    validates :name, format: { with: /\A[a-zA-Z0-9\-\_\s]+\z/, message: "only allows alphanumeric, hypen(-), underscore(_), spaces( )" }
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :uuid, presence: true
    validates :uuid, uniqueness: true
    validates :uuid, uuid: true
    validates :host, presence: true
    validates :host, uniqueness: true
    validates :level, presence: true
    validates :level, numericality: { only_integer: true }
    validate :validateChamberRole
    
    after_initialize :setUUID
    before_validation :setRole
    after_save :setKey, if: :local
    
    private

    ##
    # setUUID will generate a RFC 4122 compliant UUID
    # and set the value on the uuid attribute on init
    # no input required and cannot be called directly

    def setUUID()
      self[:uuid] = UUID.generate unless self.uuid
    end

    ##
    # setRole will correctly set the related boolean
    # values depending on if the chamber is a master
    # secondary, or slave.  This is more of a helper
    # method that will set expected values to ensure
    # that validation passes (validateChamberRole).
    #
    # This methods output is skipped if the RAILS_ENV
    # is 'test'.  This ensures that the validation works
    # without crippling integrations for each of access.

    def setRole()
      return if ENV['RAILS_ENV'] == 'test'
      if self.master
        self.slave = false
        self.secondary = false
      end

      if self.secondary
        self.slave = true
        self.master = false
      end
      
      if self.slave
        self.master = false
      end
      
      if !self.master && !self.secondary
        self.slave = true
      end
    end
    
    ##
    # setKey will generate and set the RSA key used for
    # communications between chamber nodes.
    #
    # If the record fails to create, the creation of
    # the chamber record is also rolled back.

    def setKey
      ChamberKey.new({chamber_uuid: self.uuid}).save() unless self.key
    end
    
    ##
    # validateChamberRole is a validation method
    # leveraged by the AR validation rules on this
    # model.  This method ensures that all the
    # boolean values are correctly attributed to
    # a chamber for the specific role it plays in
    # the ecosystem.

    def validateChamberRole()
      # master cannot be secondary
      # master cannot be slave
      # master can only be attributed once
      if self.master
        self.errors.add(:secondary, "master Chambers cannot be marked as secondary") if self.secondary
        self.errors.add(:slave, "master Chambers cannot be marked as slave") if self.slave
        self.errors.add(:master, "master cannot be attributed more than once") if Chamber.where(master: true).where.not(uuid: self.uuid).exists?
      end

      # secondary cannot be master
      # secondary can only be attributed once
      if self.secondary
        self.errors.add(:master, "secondary Chambers cannot be marked as master") if self.master
        self.errors.add(:secondary, "secondary cannot be attributed more than once") if Chamber.where(secondary: true).where.not(uuid: self.uuid).exists?
      end

      # anything not master must be slave
      self.errors.add(:master, "non-master Chambers must be marked as slave") if !self.master && !self.slave
      
      # local can only be attributed once
      self.errors.add(:secondary, "secondary cannot be attributed more than once") if self.local && Chamber.where(local: true).where.not(uuid: self.uuid).exists?
    end

  end

end

app/models/chambers/chamber_key.rb
module Chambers

  ##
  # ChamberKey is responsible for
  # maintaining the RSA keys for any
  # chamber>chamber communication.
  #
  # The public key will be stored in the
  # database and shared among all nodes.
  #
  # The private key will live on the node
  # and never be exported.

  class ChamberKey < ApplicationRecord

    belongs_to :chamber, class_name: "Chamber", foreign_key: :chamber_uuid, primary_key: :uuid

    validates :chamber_uuid, presence: true
    validates :chamber_uuid, uniqueness: true
    validates :chamber_uuid, uuid: true
    validates :public, presence: true
    validates :public, uniqueness: true
    #validates_associated :chamber

    after_initialize :setRSA


    private

    ##
    # setRSA will generate a RSA keyset
    # for secure communications between
    # chambers
    def setRSA
      unless self.public
        require 'openssl'
        rsa_private = OpenSSL::PKey::RSA.generate 4096
        self.public = rsa_private.public_key.to_pem
        sys_uuid = File.open('/sys/class/dmi/id/product_uuid', 'r').read().gsub(/\n/, '')
        private = File.open("#{ENV['RSA_INSTALL_DIR']}/#{sys_uuid}", "wb")
        private.puts rsa_private.to_pem
        private.close
      end
    end

  end
end

app/controllers/chambers/application_controller.rb
module Chambers
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/chambers/chambers_controller.rb
require_dependency "chambers/application_controller"

module Chambers
  class ChambersController < ApplicationController
    before_action :set_chamber, only: [:show, :edit, :update, :destroy]
    protect_from_forgery with: :null_session, if: Proc.new {|c| c.request.format.json? }

    # GET /chambers
    def index
      @chambers = Chamber.all
    end

    # GET /chambers/1
    def show
    end

    # GET /chambers/new
    def new
      @chamber = Chamber.new
    end

    # GET /chambers/1/edit
    def edit
    end

    # POST /chambers
    def create
      @chamber = Chamber.new(chamber_params)

      if @chamber.save
        redirect_to @chamber, notice: 'Chamber was successfully created.' unless request.format.json?
      else
        response.status = @chamber.errors ? 409 : 500
        render :new unless request.format.json?
      end
    end

    # PATCH/PUT /chambers/1
    def update
      if @chamber.update(chamber_params)
        redirect_to @chamber, notice: 'Chamber was successfully updated.' unless request.format.json?
      else
        response.status = @chamber.errors ? 409 : 500
        render :edit unless request.format.json?
      end
    end

    # DELETE /chambers/1
    def destroy
      @chamber.destroy
      redirect_to chambers_url, notice: 'Chamber was successfully destroyed.' unless request.format.json?
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_chamber
        if request.format.json?
          @chamber = Chamber.find_by_uuid(params[:id])
        else
          @chamber = Chamber.find(params[:id])
        end
      end

      # Only allow a trusted parameter "white list" through.
      def chamber_params
        params.require(:chamber).permit(:name,:host,:level,:master,:slave,:secondary,:local,:active)
      end
  end
end

app/helpers/chambers/application_helper.rb
module Chambers
  module ApplicationHelper
  end
end

app/helpers/chambers/chambers_helper.rb
module Chambers
  module ChambersHelper
  end
end

app/views/chambers/chambers/_form.html.erb
<%= form_with(model: chamber, local: true) do |form| %>
  <% if chamber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chamber.errors.count, "error") %> prohibited this chamber from being saved:</h2>

      <ul>
        <% chamber.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name, placeholder: "Name" %><br />
  <%= form.text_field :host, placeholder: "Host" %><br />
  <%= form.number_field :level, placeholder: "Floor Level" %><br />
  Master: <%= form.check_box :master %><br />
  Slave: <%= form.check_box :slave %><br />
  Secondary: <%= form.check_box :secondary %><br />
  Local: <%= form.check_box :local %><br />
  Active: <%= form.check_box :active %><br />


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chambers/chambers/edit.html.erb
<h1>Editing Chamber</h1>

<%= render 'form', chamber: @chamber %>

<%= link_to 'Show', @chamber %> |
<%= link_to 'Back', chambers_path %>

app/views/chambers/chambers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chambers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chambers.each do |chamber| %>
      <tr>
        <td><%= chamber.id %></td>
        <td><%= chamber.uuid %></td>
        <td><%= chamber.name %></td>
        <td><%= chamber.host %></td>
        <td><%= chamber.level %></td>
        <td><%= chamber.active %></td>
        <td><%= chamber.created_at %></td>
        <td><%= chamber.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chamber', new_chamber_path %>

app/views/chambers/chambers/new.html.erb
<h1>New Chamber</h1>

<%= render 'form', chamber: @chamber %>

<%= link_to 'Back', chambers_path %>

app/views/chambers/chambers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chamber_path(@chamber) %> |
<%= link_to 'Back', chambers_path %>

app/views/layouts/chambers/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chambers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "chambers/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>